version: '3'
services:
  ros:
    image: blinglnav/robotics-ros:arm
    container_name: ros
    environment:
      - IP_OF_REMOTE_PC=${IP_OF_REMOTE_PC}
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITSHM=1
    # stdin_open: true
    # tty: true
    volumes:
      - bin:/usr/bin/
      - ros_volume_root:/root/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
volumes:
  ros_volume_root:
  bin: